### ISSUE TITLE
WooCommerce API

### ISSUE THREAD

**Issue by kevin25** [zackha/nuxtcommerce#149]
Thank you for your great work. Connecting from GrapSQL is quite slow. can you support API? It's faster and easier.

**Comment by zackha** [comment]
Hey @kevin25,

Thank you for your interest in the project. I had only tested the WooCommerce API for admin tasks, but for front-end operations, I’ve always worked with GraphQL. The better the GPU and RAM capacity of the server where WooCommerce is running, the better the response time. If you'd like, you can try @scottyzen 's [Woonuxt](https://github.com/scottyzen/woonuxt), which offers a faster experience.

Best Regards,

**Comment by kevin25** [comment]
Thank you so much. We're hosting it on AWS with 128GB of memory. However, the store has 30k variable products. As you see, the database size is too big and slow. API is the only way that will work better.

**Comment by zackha** [comment]
Is there a store on GitHub that uses the WooCommerce API? I'm not sure if it would be faster than GraphQL.

**Comment by kevin25** [comment]
You can try this https://nextjs-woocommerce-restapi-virid.vercel.app/
