### ISSUE TITLE
Payment Options

### ISSUE THREAD

**Issue by thubamamba** [zackha/nuxtcommerce#194]
This is such a cool project. This is not much of an issue but rather, I am curious as to the possibility of passing the checkout from the Vue app to the Woocommerce app in order to complete payments, as a workaround to the complexity of adding custom payment solutions @zackha. Thanks for your assistance.

**Comment by zackha** [comment]
hey @thubamamba,

You can find the solution you are looking for at this link: [https://scottbolinger.com/woocommerce-app-react-wpgraphql/](https://scottbolinger.com/woocommerce-app-react-wpgraphql/)
